version: "3"
services:
  web:
    build: .
    image: masarakki/jfroxy
    restart: always
    environment:
      REDIS_URL: redis://redis:6379
    env_file:
      - .env.production
    ports:
      - "80:80"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: always
