version: "3"
services:
  web:
    build: .
    image: masarakki/jfroxy
    restart: always
    environment:
      REDIS_URL: redis://redis:6379
    env_file:
      - .env.production
    ports:
      - "80:80"
    depends_on:
      - redis
  redis:
    image: redis:alpine@sha256:69f2c586c8a7e9cce4ae1ee9bbaf60bc4bb5f4bb3880e4ed022b1fd758a7cab9
    restart: always
