version: "3"
services:
  web:
    build: .
    image: masarakki/jfroxy
    restart: always
    environment:
      REDIS_URL: redis://redis:6379
    env_file:
      - .env.production
    ports:
      - "80:80"
    depends_on:
      - redis
  redis:
    image: redis:alpine@sha256:c5e375abb885e6b2021c0377879e4890bf76f9065b8922ffc113f2b226b9fc17
    restart: always
