version: "3"
services:
  web:
    build: .
    image: masarakki/jfroxy
    restart: always
    environment:
      REDIS_URL: redis://redis:6379
    env_file:
      - .env.production
    ports:
      - "80:80"
    depends_on:
      - redis
  redis:
    image: redis:alpine@sha256:8096655e437712b07503796fb64d81359256cfcff0ab29d95a7da72863786efb
    restart: always
