name: Ruby
on: [push]
jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v1
    - name: setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: rake spec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake spec
